# See https://shopify.dev/api/checkout-extensions/checkout/configuration

api_version = "2024-04"

[[extensions]]
name = "checkout-ui"
handle = "checkout-ui"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/checkout.ts"
target = "purchase.checkout.shipping-option-list.render-after"
