version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
