# See https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "129b38b0826589d3ecf41e0c5cc7e32d"
name = "GZETA x Wikini"
handle = "gzeta-x-wikini"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
scopes = ""

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/api/auth"]

[build]
include_config_on_deploy = true

[pos]
embedded = false

[webhooks]
api_version = "2024-04"
