name: Keep alive

on:
  schedule:
    - cron: '0 0 1/7 * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
