name: Keep Alive

permissions:
  actions: write
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
        with:
          COMMIT_MESSAGE: "chore(keep-alive): automated commit"
