name: Keep Alive

permissions:
  actions: write
  contents: read

on:
  schedule:
    - cron: "0 0 1/7 * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          commit_message: "build(keep-alive): automated commit"
          use_api: false
