name: Sync collections status

on:
  workflow_dispatch:
  repository_dispatch:
    types: ['Sync collections status']
  schedule:
    - cron: '0 */3 * * *'

jobs:
  sync-collections-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm run action sync-collections-status --event ${{ github.event_name }}
        name: Run action sync-collections-status
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_COLLECTION_STATUS_TABLE_ID: ${{ secrets.AIRTABLE_COLLECTION_STATUS_TABLE_ID }}
          AIRTABLE_RUNS_TABLE_ID: ${{ secrets.AIRTABLE_RUNS_TABLE_ID }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_COLLECTION_METAFIELD: ${{ secrets.SHOPIFY_COLLECTION_METAFIELD }}
          SHOPIFY_STORE_ID: ${{ secrets.SHOPIFY_STORE_ID }}
