name: Sync collections status

on:
  workflow_dispatch:
  repository_dispatch:
    types: ['Sync collections status']
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync-collections-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm run action sync-collections-status --event ${{ github.event_name }} --runId ${{ github.run_id }}
        name: Run action sync-collections-status
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
          GOOGLE_SHEETS_SYNC_COLLECTIONS_STATUS_SHEET: ${{ secrets.GOOGLE_SHEETS_SYNC_COLLECTIONS_STATUS_SHEET }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_COLLECTION_METAFIELD: ${{ secrets.SHOPIFY_COLLECTION_METAFIELD }}
          SHOPIFY_STORE_ID: ${{ secrets.SHOPIFY_STORE_ID }}
