name: Sync products quantity

on:
  workflow_dispatch:
  repository_dispatch:
    types: ['Sync products quantity']

jobs:
  sync-products-quantity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm run action sync-products-quantity --event ${{ github.event_name }} --retries 8 --runId ${{ github.run_id }}
        name: Run action sync-products-quantity
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_BASE_SHARED_ID: ${{ secrets.AIRTABLE_BASE_SHARED_ID }}
          AIRTABLE_PRODUCT_QUANTITY_TABLE_ID: ${{ secrets.AIRTABLE_PRODUCT_QUANTITY_TABLE_ID }}
          AIRTABLE_RUNS_TABLE_ID: ${{ secrets.AIRTABLE_RUNS_TABLE_ID }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_LOCATION_ID: ${{ secrets.SHOPIFY_LOCATION_ID }}
          SHOPIFY_STORE_ID: ${{ secrets.SHOPIFY_STORE_ID }}
          PIM_API_URL: ${{ secrets.PIM_API_URL }}
          PIM_TOKEN: ${{ secrets.PIM_TOKEN }}
          PIM_VERIFY_ENDPOINT: ${{ secrets.PIM_VERIFY_ENDPOINT }}
