name: Sync Products Quantity

on:
  workflow_dispatch:
  repository_dispatch:
    types: ['Sync Products Quantity']
  workflow_dispatch:

jobs:
  sync-products-quantity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm run action sync-products-quantity --event ${{ github.event_name }} --retries ${{ env.RETRIES }} --runId ${{ github.run_id }}
        name: Run action sync-products-quantity
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GOOGLE_SHEETS_SPREADSHEET_ID: ${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}
          GOOGLE_SHEETS_SYNC_PRODUCTS_QUANTITY_SHEET: ${{ secrets.GOOGLE_SHEETS_SYNC_PRODUCTS_QUANTITY_SHEET }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_LOCATION_ID: ${{ secrets.SHOPIFY_LOCATION_ID }}
          SHOPIFY_STORE_ID: ${{ secrets.SHOPIFY_STORE_ID }}
          PIM_API_URL: ${{ secrets.PIM_API_URL }}
          PIM_TOKEN: ${{ secrets.PIM_TOKEN }}
          PIM_VERIFY_ENDPOINT: ${{ secrets.PIM_VERIFY_ENDPOINT }}
          RETRIES: ${{ secrets.RETRIES || 3 }}
